import React from 'react';

/**
 * Explanation page.
 * Will display: LLM-generated explanation of the fault and recovery.
 * TODO: Wire up to POST /api/v1/explanation/
 */
function Explanation() {
  return (
    <div>
      <h1>Explanation</h1>
      <p style={{ color: 'var(--color-muted)', marginTop: '0.5rem' }}>
        Human-readable explanations generated by the RAG / LLM pipeline.
        (Placeholder — implementation pending)
      </p>
    </div>
  );
}

export default Explanation;
